"""
NeuroAssist AI v2 — PDF Report Generation Service
Generates clinical PDF reports via ReportLab with Jinja2-templated content.
Every field is populated from real computed data — no placeholder text.
Regulatory disclaimer appears on every page.
"""

import os
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from backend.config import settings


DISCLAIMER = (
    "DISCLAIMER: Investigational software. Not a substitute for clinical judgment. "
    "Not FDA/CE cleared. This report is generated by NeuroAssist AI for "
    "decision-support purposes only. All clinical decisions should be made "
    "by the treating physician."
)


def generate_pdf(report: dict, doctor: dict, prediction: dict = None) -> str:
    """
    Generate a clinical PDF report from real computed data.
    Returns the file path of the generated PDF.
    """
    os.makedirs(settings.pdf_output_dir, exist_ok=True)
    pdf_path = os.path.join(settings.pdf_output_dir, f"report_{report['_id'][:8]}.pdf")

    doc = SimpleDocTemplate(
        pdf_path,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=25 * mm,
        bottomMargin=25 * mm,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle", parent=styles["Title"],
        fontSize=20, textColor=colors.HexColor("#1a237e"),
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "CustomSubtitle", parent=styles["Heading2"],
        fontSize=14, textColor=colors.HexColor("#283593"),
        spaceBefore=12, spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "CustomBody", parent=styles["Normal"],
        fontSize=10, leading=14, alignment=TA_JUSTIFY,
    )
    disclaimer_style = ParagraphStyle(
        "Disclaimer", parent=styles["Normal"],
        fontSize=7, textColor=colors.HexColor("#b71c1c"),
        alignment=TA_CENTER, spaceBefore=10,
    )
    header_style = ParagraphStyle(
        "Header", parent=styles["Normal"],
        fontSize=8, textColor=colors.gray, alignment=TA_CENTER,
    )

    elements = []

    # ---- Header ----
    elements.append(Paragraph("🧠 NeuroAssist AI — Clinical Decision Support Report", title_style))
    elements.append(Paragraph(DISCLAIMER, disclaimer_style))
    elements.append(Spacer(1, 12))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a237e")))
    elements.append(Spacer(1, 12))

    # ---- Report Metadata ----
    meta_data = [
        ["Report ID:", report["_id"][:12]],
        ["Generated:", report.get("created_at", datetime.now()).strftime("%Y-%m-%d %H:%M UTC")],
        ["Clinician:", doctor.get("full_name", "N/A")],
        ["Specialization:", doctor.get("specialization", "N/A")],
        ["License #:", doctor.get("medical_license_number", "N/A")],
        ["Language:", report.get("language", "en").upper()],
        ["Model Version:", report.get("model_version", "N/A")],
        ["Trace ID:", report.get("trace_id", "N/A")],
    ]

    if report.get("patient_id"):
        meta_data.insert(2, ["Patient Record ID:", report["patient_id"][:12]])

    meta_table = Table(meta_data, colWidths=[120, 350])
    meta_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1a237e")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 16))

    # ---- Summary Section ----
    if report.get("summary"):
        elements.append(Paragraph("Summary", subtitle_style))
        elements.append(Paragraph(report["summary"].replace("\n", "<br/>"), body_style))
        elements.append(Spacer(1, 10))

    # ---- Detailed Findings ----
    if report.get("detailed_findings"):
        elements.append(Paragraph("Detailed Findings", subtitle_style))
        elements.append(Paragraph(report["detailed_findings"].replace("\n", "<br/>"), body_style))
        elements.append(Spacer(1, 10))

    # ---- XAI Interpretation ----
    if report.get("xai_interpretation"):
        elements.append(Paragraph("Explainable AI Interpretation Guide", subtitle_style))
        elements.append(Paragraph(report["xai_interpretation"].replace("\n", "<br/>"), body_style))
        elements.append(Spacer(1, 10))

    # ---- Risk Summary ----
    if report.get("risk_summary"):
        elements.append(Paragraph("Risk Assessment Summary", subtitle_style))
        elements.append(Paragraph(report["risk_summary"].replace("\n", "<br/>"), body_style))
        elements.append(Spacer(1, 10))

    # ---- Recommendations ----
    recs = report.get("recommendations", {})
    if recs:
        elements.append(Paragraph("Clinical Recommendations", subtitle_style))

        # Specialists
        if recs.get("specialists"):
            elements.append(Paragraph("<b>Recommended Specialists:</b>", body_style))
            for spec in recs["specialists"]:
                elements.append(Paragraph(
                    f"• <b>{spec['name']}</b> ({spec['specialty']}): {spec['rationale']}",
                    body_style,
                ))
            elements.append(Spacer(1, 6))

        # Exercises
        if recs.get("exercises"):
            elements.append(Paragraph("<b>Recommended Activities:</b>", body_style))
            for ex in recs["exercises"]:
                elements.append(Paragraph(
                    f"• <b>{ex['name']}</b>: {ex['description']} — {ex['frequency']}",
                    body_style,
                ))
            elements.append(Spacer(1, 6))

        # Caregiver guidance
        if recs.get("caregiver_guidance"):
            elements.append(Paragraph("<b>Caregiver Guidance:</b>", body_style))
            for g in recs["caregiver_guidance"]:
                elements.append(Paragraph(f"• {g}", body_style))

        elements.append(Spacer(1, 10))

    # ---- XAI Heatmaps Embedding ----
    temp_files = []
    if prediction and "xai_overlays" in prediction and prediction["xai_overlays"]:
        elements.append(Paragraph("Live Explainability (XAI) Overlays", subtitle_style))
        overlays = prediction["xai_overlays"]
        try:
            import tempfile
            import base64
            from reportlab.platypus import Image as RLImage
            
            row_images = []
            row_labels = []
            
            methods = [
                ("gradcam", "Grad-CAM"),
                ("gradcam_plus_plus", "Grad-CAM++"),
                ("hirescam", "HiResCAM")
            ]
            
            for key, label in methods:
                overlay_key = f"{key}_overlay"
                if overlay_key in overlays and overlays[overlay_key]:
                    # Write base64 string to temp file
                    img_data = base64.b64decode(overlays[overlay_key])
                    tf = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
                    tf.write(img_data)
                    tf.close()
                    temp_files.append(tf.name)
                    
                    # 45mm x 45mm image flowable
                    rl_img = RLImage(tf.name, width=45*mm, height=45*mm)
                    row_images.append(rl_img)
                    row_labels.append(Paragraph(f"<b>{label}</b>", body_style))
            
            if row_images:
                # Add labels row and images row to a Table
                xai_table = Table([row_labels, row_images], colWidths=[55*mm, 55*mm, 55*mm])
                xai_table.setStyle(TableStyle([
                    ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ]))
                elements.append(xai_table)
                elements.append(Spacer(1, 10))
                
        except Exception as e:
            logger.warning(f"Failed to embed XAI images in PDF: {e}")

    # ---- Citations ----
    citations = report.get("rag_citations", [])
    if citations:
        elements.append(Paragraph("Evidence Sources", subtitle_style))
        for i, cite in enumerate(citations, 1):
            elements.append(Paragraph(
                f"[{i}] <b>{cite.get('source', 'Unknown')}</b>: {cite.get('excerpt', '')[:150]}...",
                body_style,
            ))
        elements.append(Spacer(1, 10))

    # ---- Footer Disclaimer ----
    elements.append(Spacer(1, 20))
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.gray))
    elements.append(Paragraph(DISCLAIMER, disclaimer_style))
    elements.append(Paragraph(
        f"Generated by NeuroAssist AI v{settings.app_version} | "
        f"Decision Support Mode | {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}",
        header_style,
    ))

    try:
        doc.build(elements)
    finally:
        # Clean up temp image files
        for tf_name in temp_files:
            try:
                os.remove(tf_name)
            except Exception:
                pass
    return pdf_path
